name: Check

# Run this workflow every time a new commit pushed to your repository on a branch that is not master
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get master commit
        run: git rev-parse origin/master
      - name: Unit tests
        run: bash ./gradlew runAffectedUnitTests -Paffected_module_detector.enable
      - name: Get changed files
        run: git --no-pager diff --name-only 6e23b7c624fdbe30bb610d8f2f399a97bf311d24
      - name: Upload test output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated output file
          path: output/output.log
